# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nextcloud.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fnextcloud.proto\x12\tnextcloud\"6\n\x11UploadFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"5\n\x12UploadFileResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1b\n\x0b\x46ileRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x1f\n\x0c\x46ileResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x32\x99\x01\n\x10NextcloudService\x12:\n\x07GetFile\x12\x16.nextcloud.FileRequest\x1a\x17.nextcloud.FileResponse\x12I\n\nUploadFile\x12\x1c.nextcloud.UploadFileRequest\x1a\x1d.nextcloud.UploadFileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nextcloud_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UPLOADFILEREQUEST']._serialized_start=30
  _globals['_UPLOADFILEREQUEST']._serialized_end=84
  _globals['_UPLOADFILERESPONSE']._serialized_start=86
  _globals['_UPLOADFILERESPONSE']._serialized_end=139
  _globals['_FILEREQUEST']._serialized_start=141
  _globals['_FILEREQUEST']._serialized_end=168
  _globals['_FILERESPONSE']._serialized_start=170
  _globals['_FILERESPONSE']._serialized_end=201
  _globals['_NEXTCLOUDSERVICE']._serialized_start=204
  _globals['_NEXTCLOUDSERVICE']._serialized_end=357
# @@protoc_insertion_point(module_scope)
