from enum import Enum, auto


class UserRole(str, Enum):
    VISITOR = "VISITOR"
    EDUCATOR = "EDUCATOR"
    EXPERT = "EXPERT"
    PERCEIVE_EXPERT = "PERCEIVE_EXPERT"
    PERCEIVE_DEVELOPER = "PERCEIVE_DEVELOPER"
    ADMIN = "ADMIN"
